services:
  backend:
    container_name: syno-slideshow-nodered
    image: 'nodered/node-red'
    ports:
      - "1880:1880"
    volumes:
      - ./node_red_data:/data

  nginx:
    container_name: syno-slideshow-nginx
    image: nginx:1-alpine
    ports:
      - "8089:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro